import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  String _locale = 'en'; // default language code
  bool _isFirstTime = true;

  String get locale => _locale;
  bool get isFirstTime => _isFirstTime;
  bool get isBangla => _locale == 'bn';

  LanguageProvider() {
    _loadPreferences();
  }

  // Load language settings from SharedPreferences
  Future<void> _loadPreferences() async {
    final prefs = await SharedPreferences.getInstance();
    _locale = prefs.getString('language_code') ?? 'en';
    _isFirstTime = prefs.getBool('first_time_launch') ?? true;
    notifyListeners();
  }

  // Change language and save to SharedPreferences
  Future<void> setLanguage(String langCode) async {
    _locale = langCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', langCode);
    notifyListeners();
  }

  // Set first time launch completed
  Future<void> setFirstTimeCompleted() async {
    _isFirstTime = false;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('first_time_launch', false);
    notifyListeners();
  }

  // Translation dictionary mapping
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Kuakata Travel Guide',
      'tagline': 'Daughter of the Ocean',
      'select_language': 'Select Language',
      'select_language_sub': 'Please choose your preferred language to continue',
      'continue_btn': 'Continue',
      'hotel_booking': 'Hotel Booking',
      'bike_booking': 'Bike Booking',
      'van_booking': 'Van Booking',
      'board_booking': 'Board Booking',
      'boat_booking': 'Boat Booking',
      'ship_booking': 'Ship Booking',
      'food_order': 'Food Order',
      'tourist_police': 'Tourist Police',
      'ambulance': 'Ambulance',
      'other_info': 'Other Information',
      'explore_spots': 'Popular Tourist Spots',
      'settings': 'Settings',
      'bookings': 'My Bookings',
      'home': 'Home',
      'emergency': 'Emergency',
      'change_lang': 'Change Language',
      'backend_url': 'Backend URL / API Base',
      'save': 'Save',
      'save_success': 'Backend configuration updated successfully!',
      'theme_mode': 'Theme Mode',
      'theme_sub': 'Choose app appearance preference',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'about_kuakata': 'About Kuakata',
      'about_text': 'Kuakata is a rare scenic beauty spot on the southernmost tip of Bangladesh, offering a panoramic view of the sandy beach and the unique opportunity to watch both sunrise and sunset over the Bay of Bengal.',
      'about_us': 'About Us',
      'founder_title': 'Founder',
      'founder_name': 'Kabir Hossain Shuvo',
      'founder_desc': 'Director, Kuakata Multimedia & Social Entrepreneur',
      'developer_title': 'Developer',
      'developer_name': 'Baluka Soft',
      'book_now': 'Book Now',
      'name': 'Full Name',
      'phone': 'Phone Number',
      'date': 'Select Date',
      'time': 'Select Time',
      'duration': 'Duration (Days/Hours)',
      'passengers': 'Number of Passengers/Rooms',
      'category': 'Category / Class',
      'notes': 'Special Instructions / Notes',
      'submit_booking': 'Submit Booking Request',
      'success': 'Success',
      'booking_success': 'Your booking request has been submitted successfully!',
      'close': 'Close',
      'restaurants': 'Popular Restaurants',
      'add_to_cart': 'Add to Cart',
      'cart': 'Your Cart',
      'total': 'Total',
      'place_order': 'Place Order',
      'order_success': 'Your food order has been placed successfully!',
      'no_bookings': 'No active bookings found.',
      'helpline_desc': 'Emergency contacts for quick support during your tour.',
      'call': 'Call Now',
      'back': 'Back',
      'weather_title': 'Kuakata Weather',
      'weather_temp': '29°C',
      'weather_cond': 'Sunny & Pleasant',
      'tide_status': 'High Tide: 11:30 AM',
      'view_details': 'View Details',
      'spot_beach_desc': 'The main sandy beach, famous for viewing both sunrise and sunset.',
      'spot_gangamati_desc': 'A dense evergreen forest on the eastern side, ideal for seeing sunrise.',
      'spot_jhaubon_desc': 'A beautiful forest of Casuarina trees offering fresh air and picnic spots.',
      'spot_redcrab_desc': 'A serene beach where thousands of red crabs emerge, creating a red carpet.',
      'spot_temple_desc': 'Misripara Buddhist Temple housing the largest statue of Buddha in the region.',
      'connecting': 'Connecting to backend...',
      'offline_mode': 'Offline/Mock Mode Active',
      'login': 'Log In',
      'register': 'Create Account',
      'logout': 'Log Out',
      'profile': 'User Profile',
      'my_complaints': 'My Complaints',
      'file_complaint': 'File a Complaint',
      'subject': 'Subject',
      'description': 'Description',
      'photo': 'Attachment Photo',
      'select_photo': 'Select Photo',
      'write_review': 'Write a Review',
      'rating': 'Rating',
      'comment': 'Comment',
      'public_reviews': 'Public Reviews & Ratings',
      'name_field': 'Full Name',
      'address_field': 'Address',
      'email_field': 'Email Address (Optional)',
      'mobile_number': 'Mobile Number',
      'login_identifier': 'Mobile Number or Email',
      'hotel_stayed': 'Hotel Stayed At',
      'hotel_name': 'Hotel Name',
      'room_number': 'Room Number',
      'pin': 'PIN',
      'retype_pin': 'Retype PIN',
      'pin_mismatch': 'PINs do not match',
      'forgot_pin': 'Forgot PIN?',
      'reset_pin': 'Reset PIN',
      'enter_new_pin': 'Enter New PIN',
      'pin_error': 'Incorrect PIN',
      'pin_validation': 'PIN must be exactly 6 digits',
      'reset_success': 'PIN reset successfully!',
      'user_not_found': 'User not found with these details',
      'room_reviews': 'Room Reviews & Ratings',
      'submit_review': 'Submit Review',
      'submit_complaint': 'Submit Complaint',
      'complaint_success': 'Complaint filed successfully!',
      'review_success': 'Review posted successfully!',
      'no_complaints': 'No complaints filed yet.',
      'login_required': 'Login Required',
      'login_required_desc': 'You must be logged in to access this feature.',
      'super_admin': 'Super Admin',
      'admin_username': 'Admin Username',
      'admin_password': 'Admin Password',
      'admin_login': 'Admin Login',
      'admin_login_success': 'Logged in successfully!',
    },
    'bn': {
      'app_title': 'কুয়াকাটা ভ্রমণ নির্দেশিকা',
      'tagline': 'সাগর কন্যা কুয়াকাটা',
      'select_language': 'ভাষা নির্বাচন করুন',
      'select_language_sub': 'অনুগ্রহ করে এগিয়ে যাওয়ার জন্য আপনার পছন্দের ভাষাটি বেছে নিন',
      'continue_btn': 'এগিয়ে যান',
      'hotel_booking': 'হোটেল বুকিং',
      'bike_booking': 'বাইক বুকিং',
      'van_booking': 'ভ্যান বুকিং',
      'board_booking': 'বোর্ড বুকিং',
      'boat_booking': 'নৌকা বুকিং',
      'ship_booking': 'লঞ্চ ও জাহাজ বুকিং',
      'food_order': 'খাবার অর্ডার',
      'tourist_police': 'ট্যুরিস্ট পুলিশ',
      'ambulance': 'অ্যাম্বুলেন্স',
      'other_info': 'অন্যান্য তথ্য',
      'explore_spots': 'জনপ্রিয় দর্শনীয় স্থান',
      'settings': 'সেটিংস',
      'bookings': 'আমার বুকিং',
      'home': 'হোম',
      'emergency': 'জরুরী সেবা',
      'change_lang': 'ভাষা পরিবর্তন করুন',
      'backend_url': 'ব্যাকএন্ড আইপি / এপিআই বেস',
      'save': 'সংরক্ষণ করুন',
      'save_success': 'ব্যাকএন্ড কনফিগারেশন সফলভাবে আপডেট করা হয়েছে!',
      'theme_mode': 'থিম মোড',
      'theme_sub': 'আপনার পছন্দের অ্যাপ সংস্করণ নির্বাচন করুন',
      'light_mode': 'লাইট মোড',
      'dark_mode': 'ডার্ক মোড',
      'about_kuakata': 'কুয়াকাটা সম্পর্কে',
      'about_text': 'কুয়াকাটা বাংলাদেশের দক্ষিণ-পশ্চিমাঞ্চলের একটি অনন্য প্রাকৃতিক সৌন্দর্যমণ্ডিত স্থান, যা একই সৈকত থেকে সূর্যোদয় এবং সূর্যাস্ত দেখার এক বিরল সুযোগ প্রদান করে।',
      'about_us': 'আমাদের সম্পর্কে',
      'founder_title': 'প্রতিষ্ঠাতা',
      'founder_name': 'কবির হোসাইন শুভ',
      'founder_desc': 'পরিচালক, কুয়াকাটা মাল্টিমিডিয়া এবং সামাজিক উদ্যোক্তা',
      'developer_title': 'ডেভেলপার',
      'developer_name': 'বালুকা সফট',
      'book_now': 'বুক করুন',
      'name': 'সম্পূর্ণ নাম',
      'phone': 'মোবাইল নম্বর',
      'date': 'তারিখ নির্বাচন করুন',
      'time': 'সময় নির্বাচন করুন',
      'duration': 'সময়কাল (দিন/ঘণ্টা)',
      'passengers': 'যাত্রী / রুমের সংখ্যা',
      'category': 'শ্রেণী / ক্যাটাগরি',
      'notes': 'বিশেষ নির্দেশাবলী / নোট',
      'submit_booking': 'বুকিং অনুরোধ পাঠান',
      'success': 'সফল',
      'booking_success': 'আপনার বুকিং অনুরোধটি সফলভাবে পাঠানো হয়েছে!',
      'close': 'বন্ধ করুন',
      'restaurants': 'জনপ্রিয় রেস্তোরাঁ',
      'add_to_cart': 'কার্টে যোগ করুন',
      'cart': 'আপনার কার্ট',
      'total': 'মোট',
      'place_order': 'অর্ডার করুন',
      'order_success': 'আপনার খাবার অর্ডারটি সফলভাবে সম্পন্ন হয়েছে!',
      'no_bookings': 'কোন সক্রিয় বুকিং পাওয়া যায়নি।',
      'helpline_desc': 'ভ্রমণের সময় দ্রুত সহায়তার জন্য জরুরী যোগাযোগ নম্বর সমূহ।',
      'call': 'কল করুন',
      'back': 'ফিরে যান',
      'weather_title': 'কুয়াকাটার আবহাওয়া',
      'weather_temp': '২৯° সেলসিয়াস',
      'weather_cond': 'রৌদ্রোজ্জ্বল ও মনোরম',
      'tide_status': 'জোয়ার: সকাল ১১:৩০ মিনিট',
      'view_details': 'বিস্তারিত দেখুন',
      'spot_beach_desc': 'প্রধান সৈকত, যা সূর্যোদয় এবং সূর্যাস্ত উভয় দেখার জন্য বিখ্যাত।',
      'spot_gangamati_desc': 'পূর্ব দিকের একটি ঘন চিরহরিৎ বন, সূর্যোদয় দেখার জন্য আদর্শ।',
      'spot_jhaubon_desc': 'ঝাউ গাছের একটি সুন্দর বন যা তাজা বাতাস এবং পিকনিকের স্পট প্রদান করে।',
      'spot_redcrab_desc': 'একটি শান্ত সৈকত যেখানে হাজার হাজার লাল কাঁকড়া উঠে আসে, লাল গালিচা তৈরি করে।',
      'spot_temple_desc': 'মিশ্রীপাড়া বৌদ্ধ মন্দির যেখানে এই অঞ্চলের সবচেয়ে বড় বুদ্ধ মূর্তি রয়েছে।',
      'connecting': 'ব্যাকএন্ডের সাথে সংযুক্ত হচ্ছে...',
      'offline_mode': 'অহলাইন/মক মোড সক্রিয়',
      'login': 'লগ ইন',
      'register': 'অ্যাকাউন্ট তৈরি করুন',
      'logout': 'লগ আউট',
      'profile': 'প্রোফাইল',
      'my_complaints': 'আমার অভিযোগ সমূহ',
      'file_complaint': 'অভিযোগ দাখিল করুন',
      'subject': 'অভিযোগের বিষয়',
      'description': 'বিস্তারিত বিবরণ',
      'photo': 'ছবি সংযুক্ত করুন',
      'select_photo': 'ছবি নির্বাচন করুন',
      'write_review': 'মতামত লিখুন',
      'rating': 'রেটিং',
      'comment': 'মন্তব্য',
      'public_reviews': 'পাবলিক রিভিউ ও রেটিং',
      'name_field': 'সম্পূর্ণ নাম',
      'address_field': 'ঠিকানা',
      'email_field': 'ইমেইল ঠিকানা (ঐচ্ছিক)',
      'mobile_number': 'মোবাইল নম্বর',
      'login_identifier': 'মোবাইল নম্বর বা ইমেইল',
      'hotel_stayed': 'যে হোটেলে ছিলেন',
      'hotel_name': 'হোটেলের নাম',
      'room_number': 'রুম নম্বর',
      'pin': 'পিন',
      'retype_pin': 'পিন পুনরায় লিখুন',
      'pin_mismatch': 'পিন নম্বর মেলেনি',
      'forgot_pin': 'পিন ভুলে গেছেন?',
      'reset_pin': 'পিন রিসেট করুন',
      'enter_new_pin': 'নতুন পিন লিখুন',
      'pin_error': 'ভুল পিন নম্বর',
      'pin_validation': 'পিন অবশ্যই ৬ ডিজিট হতে হবে',
      'reset_success': 'পিন সফলভাবে রিসেট করা হয়েছে!',
      'user_not_found': 'প্রদত্ত তথ্যে কোনো ব্যবহারকারী পাওয়া যায়নি',
      'room_reviews': 'রুম রিভিউ ও রেটিং',
      'submit_review': 'মতামত পাঠান',
      'submit_complaint': 'অভিযোগ জমা দিন',
      'complaint_success': 'অভিযোগটি সফলভাবে জমা দেওয়া হয়েছে!',
      'review_success': 'মতামত সফলভাবে প্রকাশ করা হয়েছে!',
      'no_complaints': 'এখনো কোনো অভিযোগ জমা দেওয়া হয়নি।',
      'login_required': 'লগইন প্রয়োজন',
      'login_required_desc': 'এই ফিচারটি ব্যবহার করতে আপনাকে অবশ্যই লগইন করতে হবে।',
      'super_admin': 'সুপার অ্যাডমিন',
      'admin_username': 'অ্যাডমিন ইউজারনেম',
      'admin_password': 'অ্যাডমিন পাসওয়ার্ড',
      'admin_login': 'অ্যাডমিন লগইন',
      'admin_login_success': 'সফলভাবে লগইন হয়েছে',
    }
  };

  // Helper method to retrieve translated text
  String translate(String key) {
    if (_localizedValues[_locale] != null && _localizedValues[_locale]![key] != null) {
      return _localizedValues[_locale]![key]!;
    }
    return key;
  }
}
